name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranch)_$(Build.SourceVersion)

pool:
  vmImage: 'ubuntu-latest'

steps:
# Found no other way to create a credentials containing file for sbt :/
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'New-Item ~/.sbt/.azure-artifacts-credentials -Force'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo realm=https://example.com/ >> ~/.sbt/.azure-artifacts-credentials'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo host=example.com >> ~/.sbt/.azure-artifacts-credentials'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo user=feed >> ~/.sbt/.azure-artifacts-credentials'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo password=$(AZURE_ARTIFACTS_CREDENTIALS_PASSWORD) >> ~/.sbt/.azure-artifacts-credentials'

- script: |
    wget http://apt.typesafe.com/repo-deb-build-0002.deb
    sudo dpkg -i repo-deb-build-0002.deb
    sudo apt-get update
    sudo apt-get install sbt
  displayName: 'Install SBT.'

- script: sbt test
  displayName: 'Test.'

- script: sbt docker:stage
  displayName: 'Stage Dockerfile.'