name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranch)_$(Build.SourceVersion)

pool:
  vmImage: 'ubuntu-latest'

steps:
# Found no other way to create a credentials containing file for sbt :/


- script: |
    wget http://apt.typesafe.com/repo-deb-build-0002.deb
    sudo dpkg -i repo-deb-build-0002.deb
    sudo apt-get update
    sudo apt-get install sbt
  displayName: 'Install SBT.'

- script: sbt test
  displayName: 'Test.'
